import type { Metadata } from "next";
import "./globals.css";
import Navigation from "./Navigation";
import { SITE_TITLE } from "./constants";

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: SITE_TITLE,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-h-screen max-h-screen flex flex-col">
        <Navigation />
        <main className="flex-1 overflow-y-auto scroll-smooth">{children}</main>
      </body>
    </html>
  );
}
